apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
images:
  - name: profile-site
    newName: myregistry.azurecr.io/profile-site
    newTag: 0.0.1
patchesStrategicMerge: []
